---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argo
  namespace: argo
spec:
  hostnames:
  - mykubernetes.com
  parentRefs:
  - kind: Gateway
    name: cafe-gateway
    namespace: default
  rules:
  - backendRefs:
    - name: argocd-server
      port: 2746
      namespace: argo
    matches:
    - path:
        type: PathPrefix
        value: /argo
